// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/job.proto
// Protobuf Java Version: 4.27.0

public interface GetAllResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .JobResponse jobs = 1;</code>
   */
  java.util.List<JobResponse> 
      getJobsList();
  /**
   * <code>repeated .JobResponse jobs = 1;</code>
   */
  JobResponse getJobs(int index);
  /**
   * <code>repeated .JobResponse jobs = 1;</code>
   */
  int getJobsCount();
  /**
   * <code>repeated .JobResponse jobs = 1;</code>
   */
  java.util.List<? extends JobResponseOrBuilder> 
      getJobsOrBuilderList();
  /**
   * <code>repeated .JobResponse jobs = 1;</code>
   */
  JobResponseOrBuilder getJobsOrBuilder(
      int index);
}
