// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/job.proto
// Protobuf Java Version: 4.27.0

public final class Job {
  private Job() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      Job.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JobResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_JobResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetAllRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetAllResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033src/main/protobuf/job.proto\"}\n\013JobResp" +
      "onse\022\014\n\004name\030\001 \001(\t\022\022\n\nexperience\030\002 \001(\005\022\r" +
      "\n\005stack\030\003 \003(\t\022\023\n\013description\030\004 \001(\t\022\017\n\007co" +
      "mpany\030\005 \001(\t\022\027\n\017proposed_salary\030\006 \001(\005\"\017\n\r" +
      "GetAllRequest\",\n\016GetAllResponse\022\032\n\004jobs\030" +
      "\001 \003(\0132\014.JobResponse27\n\nJobService\022)\n\006Get" +
      "All\022\016.GetAllRequest\032\017.GetAllResponseB\005P\001" +
      "\210\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_JobResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_JobResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_JobResponse_descriptor,
        new java.lang.String[] { "Name", "Experience", "Stack", "Description", "Company", "ProposedSalary", });
    internal_static_GetAllRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetAllRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetAllRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetAllResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetAllResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetAllResponse_descriptor,
        new java.lang.String[] { "Jobs", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
