// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/job.proto
// Protobuf Java Version: 4.27.0

/**
 * Protobuf type {@code JobResponse}
 */
public final class JobResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:JobResponse)
    JobResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      JobResponse.class.getName());
  }
  // Use JobResponse.newBuilder() to construct.
  private JobResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private JobResponse() {
    name_ = "";
    stack_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    description_ = "";
    company_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Job.internal_static_JobResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Job.internal_static_JobResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            JobResponse.class, JobResponse.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXPERIENCE_FIELD_NUMBER = 2;
  private int experience_ = 0;
  /**
   * <code>int32 experience = 2;</code>
   * @return The experience.
   */
  @java.lang.Override
  public int getExperience() {
    return experience_;
  }

  public static final int STACK_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList stack_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string stack = 3;</code>
   * @return A list containing the stack.
   */
  public com.google.protobuf.ProtocolStringList
      getStackList() {
    return stack_;
  }
  /**
   * <code>repeated string stack = 3;</code>
   * @return The count of stack.
   */
  public int getStackCount() {
    return stack_.size();
  }
  /**
   * <code>repeated string stack = 3;</code>
   * @param index The index of the element to return.
   * @return The stack at the given index.
   */
  public java.lang.String getStack(int index) {
    return stack_.get(index);
  }
  /**
   * <code>repeated string stack = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the stack at the given index.
   */
  public com.google.protobuf.ByteString
      getStackBytes(int index) {
    return stack_.getByteString(index);
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object description_ = "";
  /**
   * <code>string description = 4;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 4;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMPANY_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object company_ = "";
  /**
   * <code>string company = 5;</code>
   * @return The company.
   */
  @java.lang.Override
  public java.lang.String getCompany() {
    java.lang.Object ref = company_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      company_ = s;
      return s;
    }
  }
  /**
   * <code>string company = 5;</code>
   * @return The bytes for company.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCompanyBytes() {
    java.lang.Object ref = company_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      company_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROPOSED_SALARY_FIELD_NUMBER = 6;
  private int proposedSalary_ = 0;
  /**
   * <code>int32 proposed_salary = 6;</code>
   * @return The proposedSalary.
   */
  @java.lang.Override
  public int getProposedSalary() {
    return proposedSalary_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
    }
    if (experience_ != 0) {
      output.writeInt32(2, experience_);
    }
    for (int i = 0; i < stack_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, stack_.getRaw(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, description_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(company_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, company_);
    }
    if (proposedSalary_ != 0) {
      output.writeInt32(6, proposedSalary_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
    }
    if (experience_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, experience_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < stack_.size(); i++) {
        dataSize += computeStringSizeNoTag(stack_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getStackList().size();
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, description_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(company_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, company_);
    }
    if (proposedSalary_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, proposedSalary_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof JobResponse)) {
      return super.equals(obj);
    }
    JobResponse other = (JobResponse) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (getExperience()
        != other.getExperience()) return false;
    if (!getStackList()
        .equals(other.getStackList())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (!getCompany()
        .equals(other.getCompany())) return false;
    if (getProposedSalary()
        != other.getProposedSalary()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + EXPERIENCE_FIELD_NUMBER;
    hash = (53 * hash) + getExperience();
    if (getStackCount() > 0) {
      hash = (37 * hash) + STACK_FIELD_NUMBER;
      hash = (53 * hash) + getStackList().hashCode();
    }
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + COMPANY_FIELD_NUMBER;
    hash = (53 * hash) + getCompany().hashCode();
    hash = (37 * hash) + PROPOSED_SALARY_FIELD_NUMBER;
    hash = (53 * hash) + getProposedSalary();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static JobResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static JobResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static JobResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static JobResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static JobResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static JobResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static JobResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static JobResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static JobResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static JobResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static JobResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static JobResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(JobResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code JobResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:JobResponse)
      JobResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Job.internal_static_JobResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Job.internal_static_JobResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              JobResponse.class, JobResponse.Builder.class);
    }

    // Construct using JobResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      experience_ = 0;
      stack_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      description_ = "";
      company_ = "";
      proposedSalary_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Job.internal_static_JobResponse_descriptor;
    }

    @java.lang.Override
    public JobResponse getDefaultInstanceForType() {
      return JobResponse.getDefaultInstance();
    }

    @java.lang.Override
    public JobResponse build() {
      JobResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public JobResponse buildPartial() {
      JobResponse result = new JobResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(JobResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.experience_ = experience_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        stack_.makeImmutable();
        result.stack_ = stack_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.description_ = description_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.company_ = company_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.proposedSalary_ = proposedSalary_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof JobResponse) {
        return mergeFrom((JobResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(JobResponse other) {
      if (other == JobResponse.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getExperience() != 0) {
        setExperience(other.getExperience());
      }
      if (!other.stack_.isEmpty()) {
        if (stack_.isEmpty()) {
          stack_ = other.stack_;
          bitField0_ |= 0x00000004;
        } else {
          ensureStackIsMutable();
          stack_.addAll(other.stack_);
        }
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getCompany().isEmpty()) {
        company_ = other.company_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getProposedSalary() != 0) {
        setProposedSalary(other.getProposedSalary());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              experience_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureStackIsMutable();
              stack_.add(s);
              break;
            } // case 26
            case 34: {
              description_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              company_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              proposedSalary_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int experience_ ;
    /**
     * <code>int32 experience = 2;</code>
     * @return The experience.
     */
    @java.lang.Override
    public int getExperience() {
      return experience_;
    }
    /**
     * <code>int32 experience = 2;</code>
     * @param value The experience to set.
     * @return This builder for chaining.
     */
    public Builder setExperience(int value) {

      experience_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 experience = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearExperience() {
      bitField0_ = (bitField0_ & ~0x00000002);
      experience_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList stack_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureStackIsMutable() {
      if (!stack_.isModifiable()) {
        stack_ = new com.google.protobuf.LazyStringArrayList(stack_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <code>repeated string stack = 3;</code>
     * @return A list containing the stack.
     */
    public com.google.protobuf.ProtocolStringList
        getStackList() {
      stack_.makeImmutable();
      return stack_;
    }
    /**
     * <code>repeated string stack = 3;</code>
     * @return The count of stack.
     */
    public int getStackCount() {
      return stack_.size();
    }
    /**
     * <code>repeated string stack = 3;</code>
     * @param index The index of the element to return.
     * @return The stack at the given index.
     */
    public java.lang.String getStack(int index) {
      return stack_.get(index);
    }
    /**
     * <code>repeated string stack = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the stack at the given index.
     */
    public com.google.protobuf.ByteString
        getStackBytes(int index) {
      return stack_.getByteString(index);
    }
    /**
     * <code>repeated string stack = 3;</code>
     * @param index The index to set the value at.
     * @param value The stack to set.
     * @return This builder for chaining.
     */
    public Builder setStack(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureStackIsMutable();
      stack_.set(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string stack = 3;</code>
     * @param value The stack to add.
     * @return This builder for chaining.
     */
    public Builder addStack(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureStackIsMutable();
      stack_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string stack = 3;</code>
     * @param values The stack to add.
     * @return This builder for chaining.
     */
    public Builder addAllStack(
        java.lang.Iterable<java.lang.String> values) {
      ensureStackIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, stack_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string stack = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStack() {
      stack_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string stack = 3;</code>
     * @param value The bytes of the stack to add.
     * @return This builder for chaining.
     */
    public Builder addStackBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureStackIsMutable();
      stack_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 4;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 4;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 4;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      description_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string description = 4;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object company_ = "";
    /**
     * <code>string company = 5;</code>
     * @return The company.
     */
    public java.lang.String getCompany() {
      java.lang.Object ref = company_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        company_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string company = 5;</code>
     * @return The bytes for company.
     */
    public com.google.protobuf.ByteString
        getCompanyBytes() {
      java.lang.Object ref = company_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        company_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string company = 5;</code>
     * @param value The company to set.
     * @return This builder for chaining.
     */
    public Builder setCompany(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      company_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string company = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCompany() {
      company_ = getDefaultInstance().getCompany();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string company = 5;</code>
     * @param value The bytes for company to set.
     * @return This builder for chaining.
     */
    public Builder setCompanyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      company_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private int proposedSalary_ ;
    /**
     * <code>int32 proposed_salary = 6;</code>
     * @return The proposedSalary.
     */
    @java.lang.Override
    public int getProposedSalary() {
      return proposedSalary_;
    }
    /**
     * <code>int32 proposed_salary = 6;</code>
     * @param value The proposedSalary to set.
     * @return This builder for chaining.
     */
    public Builder setProposedSalary(int value) {

      proposedSalary_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 proposed_salary = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearProposedSalary() {
      bitField0_ = (bitField0_ & ~0x00000020);
      proposedSalary_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:JobResponse)
  }

  // @@protoc_insertion_point(class_scope:JobResponse)
  private static final JobResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new JobResponse();
  }

  public static JobResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JobResponse>
      PARSER = new com.google.protobuf.AbstractParser<JobResponse>() {
    @java.lang.Override
    public JobResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<JobResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JobResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public JobResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

