// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/cv.proto
// Protobuf Java Version: 4.27.0

public final class Cv {
  private Cv() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      Cv.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CVResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CVResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetAllRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetAllResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032src/main/protobuf/cv.proto\"s\n\nCVRespon" +
      "se\022\014\n\004name\030\001 \001(\t\022\022\n\nprofession\030\002 \001(\t\022\022\n\n" +
      "experience\030\003 \001(\005\022\r\n\005stack\030\004 \003(\t\022\r\n\005links" +
      "\030\005 \003(\t\022\021\n\tcompanies\030\006 \003(\t\"\017\n\rGetAllReque" +
      "st\"*\n\016GetAllResponse\022\030\n\003cvs\030\001 \003(\0132\013.CVRe" +
      "sponse26\n\tCVService\022)\n\006GetAll\022\016.GetAllRe" +
      "quest\032\017.GetAllResponseB\005P\001\210\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CVResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CVResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CVResponse_descriptor,
        new java.lang.String[] { "Name", "Profession", "Experience", "Stack", "Links", "Companies", });
    internal_static_GetAllRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetAllRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetAllRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetAllResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetAllResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetAllResponse_descriptor,
        new java.lang.String[] { "Cvs", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
