// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/cv.proto
// Protobuf Java Version: 4.27.0

public interface CVResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CVResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string profession = 2;</code>
   * @return The profession.
   */
  java.lang.String getProfession();
  /**
   * <code>string profession = 2;</code>
   * @return The bytes for profession.
   */
  com.google.protobuf.ByteString
      getProfessionBytes();

  /**
   * <code>int32 experience = 3;</code>
   * @return The experience.
   */
  int getExperience();

  /**
   * <code>repeated string stack = 4;</code>
   * @return A list containing the stack.
   */
  java.util.List<java.lang.String>
      getStackList();
  /**
   * <code>repeated string stack = 4;</code>
   * @return The count of stack.
   */
  int getStackCount();
  /**
   * <code>repeated string stack = 4;</code>
   * @param index The index of the element to return.
   * @return The stack at the given index.
   */
  java.lang.String getStack(int index);
  /**
   * <code>repeated string stack = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the stack at the given index.
   */
  com.google.protobuf.ByteString
      getStackBytes(int index);

  /**
   * <code>repeated string links = 5;</code>
   * @return A list containing the links.
   */
  java.util.List<java.lang.String>
      getLinksList();
  /**
   * <code>repeated string links = 5;</code>
   * @return The count of links.
   */
  int getLinksCount();
  /**
   * <code>repeated string links = 5;</code>
   * @param index The index of the element to return.
   * @return The links at the given index.
   */
  java.lang.String getLinks(int index);
  /**
   * <code>repeated string links = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the links at the given index.
   */
  com.google.protobuf.ByteString
      getLinksBytes(int index);

  /**
   * <code>repeated string companies = 6;</code>
   * @return A list containing the companies.
   */
  java.util.List<java.lang.String>
      getCompaniesList();
  /**
   * <code>repeated string companies = 6;</code>
   * @return The count of companies.
   */
  int getCompaniesCount();
  /**
   * <code>repeated string companies = 6;</code>
   * @param index The index of the element to return.
   * @return The companies at the given index.
   */
  java.lang.String getCompanies(int index);
  /**
   * <code>repeated string companies = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the companies at the given index.
   */
  com.google.protobuf.ByteString
      getCompaniesBytes(int index);
}
