// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/cv.proto
// Protobuf Java Version: 4.27.0

/**
 * Protobuf type {@code CVResponse}
 */
public final class CVResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:CVResponse)
    CVResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      CVResponse.class.getName());
  }
  // Use CVResponse.newBuilder() to construct.
  private CVResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CVResponse() {
    name_ = "";
    profession_ = "";
    stack_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    links_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    companies_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Cv.internal_static_CVResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Cv.internal_static_CVResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CVResponse.class, CVResponse.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROFESSION_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object profession_ = "";
  /**
   * <code>string profession = 2;</code>
   * @return The profession.
   */
  @java.lang.Override
  public java.lang.String getProfession() {
    java.lang.Object ref = profession_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      profession_ = s;
      return s;
    }
  }
  /**
   * <code>string profession = 2;</code>
   * @return The bytes for profession.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProfessionBytes() {
    java.lang.Object ref = profession_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      profession_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXPERIENCE_FIELD_NUMBER = 3;
  private int experience_ = 0;
  /**
   * <code>int32 experience = 3;</code>
   * @return The experience.
   */
  @java.lang.Override
  public int getExperience() {
    return experience_;
  }

  public static final int STACK_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList stack_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string stack = 4;</code>
   * @return A list containing the stack.
   */
  public com.google.protobuf.ProtocolStringList
      getStackList() {
    return stack_;
  }
  /**
   * <code>repeated string stack = 4;</code>
   * @return The count of stack.
   */
  public int getStackCount() {
    return stack_.size();
  }
  /**
   * <code>repeated string stack = 4;</code>
   * @param index The index of the element to return.
   * @return The stack at the given index.
   */
  public java.lang.String getStack(int index) {
    return stack_.get(index);
  }
  /**
   * <code>repeated string stack = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the stack at the given index.
   */
  public com.google.protobuf.ByteString
      getStackBytes(int index) {
    return stack_.getByteString(index);
  }

  public static final int LINKS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList links_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string links = 5;</code>
   * @return A list containing the links.
   */
  public com.google.protobuf.ProtocolStringList
      getLinksList() {
    return links_;
  }
  /**
   * <code>repeated string links = 5;</code>
   * @return The count of links.
   */
  public int getLinksCount() {
    return links_.size();
  }
  /**
   * <code>repeated string links = 5;</code>
   * @param index The index of the element to return.
   * @return The links at the given index.
   */
  public java.lang.String getLinks(int index) {
    return links_.get(index);
  }
  /**
   * <code>repeated string links = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the links at the given index.
   */
  public com.google.protobuf.ByteString
      getLinksBytes(int index) {
    return links_.getByteString(index);
  }

  public static final int COMPANIES_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList companies_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string companies = 6;</code>
   * @return A list containing the companies.
   */
  public com.google.protobuf.ProtocolStringList
      getCompaniesList() {
    return companies_;
  }
  /**
   * <code>repeated string companies = 6;</code>
   * @return The count of companies.
   */
  public int getCompaniesCount() {
    return companies_.size();
  }
  /**
   * <code>repeated string companies = 6;</code>
   * @param index The index of the element to return.
   * @return The companies at the given index.
   */
  public java.lang.String getCompanies(int index) {
    return companies_.get(index);
  }
  /**
   * <code>repeated string companies = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the companies at the given index.
   */
  public com.google.protobuf.ByteString
      getCompaniesBytes(int index) {
    return companies_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(profession_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, profession_);
    }
    if (experience_ != 0) {
      output.writeInt32(3, experience_);
    }
    for (int i = 0; i < stack_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, stack_.getRaw(i));
    }
    for (int i = 0; i < links_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, links_.getRaw(i));
    }
    for (int i = 0; i < companies_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, companies_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(profession_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, profession_);
    }
    if (experience_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, experience_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < stack_.size(); i++) {
        dataSize += computeStringSizeNoTag(stack_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getStackList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < links_.size(); i++) {
        dataSize += computeStringSizeNoTag(links_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getLinksList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < companies_.size(); i++) {
        dataSize += computeStringSizeNoTag(companies_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getCompaniesList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CVResponse)) {
      return super.equals(obj);
    }
    CVResponse other = (CVResponse) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getProfession()
        .equals(other.getProfession())) return false;
    if (getExperience()
        != other.getExperience()) return false;
    if (!getStackList()
        .equals(other.getStackList())) return false;
    if (!getLinksList()
        .equals(other.getLinksList())) return false;
    if (!getCompaniesList()
        .equals(other.getCompaniesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + PROFESSION_FIELD_NUMBER;
    hash = (53 * hash) + getProfession().hashCode();
    hash = (37 * hash) + EXPERIENCE_FIELD_NUMBER;
    hash = (53 * hash) + getExperience();
    if (getStackCount() > 0) {
      hash = (37 * hash) + STACK_FIELD_NUMBER;
      hash = (53 * hash) + getStackList().hashCode();
    }
    if (getLinksCount() > 0) {
      hash = (37 * hash) + LINKS_FIELD_NUMBER;
      hash = (53 * hash) + getLinksList().hashCode();
    }
    if (getCompaniesCount() > 0) {
      hash = (37 * hash) + COMPANIES_FIELD_NUMBER;
      hash = (53 * hash) + getCompaniesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CVResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CVResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CVResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CVResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CVResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CVResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CVResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static CVResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static CVResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static CVResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CVResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static CVResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CVResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CVResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CVResponse)
      CVResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Cv.internal_static_CVResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Cv.internal_static_CVResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CVResponse.class, CVResponse.Builder.class);
    }

    // Construct using CVResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      profession_ = "";
      experience_ = 0;
      stack_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      links_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      companies_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Cv.internal_static_CVResponse_descriptor;
    }

    @java.lang.Override
    public CVResponse getDefaultInstanceForType() {
      return CVResponse.getDefaultInstance();
    }

    @java.lang.Override
    public CVResponse build() {
      CVResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public CVResponse buildPartial() {
      CVResponse result = new CVResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(CVResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.profession_ = profession_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.experience_ = experience_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        stack_.makeImmutable();
        result.stack_ = stack_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        links_.makeImmutable();
        result.links_ = links_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        companies_.makeImmutable();
        result.companies_ = companies_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CVResponse) {
        return mergeFrom((CVResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CVResponse other) {
      if (other == CVResponse.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getProfession().isEmpty()) {
        profession_ = other.profession_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getExperience() != 0) {
        setExperience(other.getExperience());
      }
      if (!other.stack_.isEmpty()) {
        if (stack_.isEmpty()) {
          stack_ = other.stack_;
          bitField0_ |= 0x00000008;
        } else {
          ensureStackIsMutable();
          stack_.addAll(other.stack_);
        }
        onChanged();
      }
      if (!other.links_.isEmpty()) {
        if (links_.isEmpty()) {
          links_ = other.links_;
          bitField0_ |= 0x00000010;
        } else {
          ensureLinksIsMutable();
          links_.addAll(other.links_);
        }
        onChanged();
      }
      if (!other.companies_.isEmpty()) {
        if (companies_.isEmpty()) {
          companies_ = other.companies_;
          bitField0_ |= 0x00000020;
        } else {
          ensureCompaniesIsMutable();
          companies_.addAll(other.companies_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              profession_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              experience_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureStackIsMutable();
              stack_.add(s);
              break;
            } // case 34
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureLinksIsMutable();
              links_.add(s);
              break;
            } // case 42
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureCompaniesIsMutable();
              companies_.add(s);
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object profession_ = "";
    /**
     * <code>string profession = 2;</code>
     * @return The profession.
     */
    public java.lang.String getProfession() {
      java.lang.Object ref = profession_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        profession_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string profession = 2;</code>
     * @return The bytes for profession.
     */
    public com.google.protobuf.ByteString
        getProfessionBytes() {
      java.lang.Object ref = profession_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        profession_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string profession = 2;</code>
     * @param value The profession to set.
     * @return This builder for chaining.
     */
    public Builder setProfession(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      profession_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string profession = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearProfession() {
      profession_ = getDefaultInstance().getProfession();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string profession = 2;</code>
     * @param value The bytes for profession to set.
     * @return This builder for chaining.
     */
    public Builder setProfessionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      profession_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int experience_ ;
    /**
     * <code>int32 experience = 3;</code>
     * @return The experience.
     */
    @java.lang.Override
    public int getExperience() {
      return experience_;
    }
    /**
     * <code>int32 experience = 3;</code>
     * @param value The experience to set.
     * @return This builder for chaining.
     */
    public Builder setExperience(int value) {

      experience_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 experience = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearExperience() {
      bitField0_ = (bitField0_ & ~0x00000004);
      experience_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList stack_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureStackIsMutable() {
      if (!stack_.isModifiable()) {
        stack_ = new com.google.protobuf.LazyStringArrayList(stack_);
      }
      bitField0_ |= 0x00000008;
    }
    /**
     * <code>repeated string stack = 4;</code>
     * @return A list containing the stack.
     */
    public com.google.protobuf.ProtocolStringList
        getStackList() {
      stack_.makeImmutable();
      return stack_;
    }
    /**
     * <code>repeated string stack = 4;</code>
     * @return The count of stack.
     */
    public int getStackCount() {
      return stack_.size();
    }
    /**
     * <code>repeated string stack = 4;</code>
     * @param index The index of the element to return.
     * @return The stack at the given index.
     */
    public java.lang.String getStack(int index) {
      return stack_.get(index);
    }
    /**
     * <code>repeated string stack = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the stack at the given index.
     */
    public com.google.protobuf.ByteString
        getStackBytes(int index) {
      return stack_.getByteString(index);
    }
    /**
     * <code>repeated string stack = 4;</code>
     * @param index The index to set the value at.
     * @param value The stack to set.
     * @return This builder for chaining.
     */
    public Builder setStack(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureStackIsMutable();
      stack_.set(index, value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string stack = 4;</code>
     * @param value The stack to add.
     * @return This builder for chaining.
     */
    public Builder addStack(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureStackIsMutable();
      stack_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string stack = 4;</code>
     * @param values The stack to add.
     * @return This builder for chaining.
     */
    public Builder addAllStack(
        java.lang.Iterable<java.lang.String> values) {
      ensureStackIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, stack_);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string stack = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStack() {
      stack_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string stack = 4;</code>
     * @param value The bytes of the stack to add.
     * @return This builder for chaining.
     */
    public Builder addStackBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureStackIsMutable();
      stack_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList links_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureLinksIsMutable() {
      if (!links_.isModifiable()) {
        links_ = new com.google.protobuf.LazyStringArrayList(links_);
      }
      bitField0_ |= 0x00000010;
    }
    /**
     * <code>repeated string links = 5;</code>
     * @return A list containing the links.
     */
    public com.google.protobuf.ProtocolStringList
        getLinksList() {
      links_.makeImmutable();
      return links_;
    }
    /**
     * <code>repeated string links = 5;</code>
     * @return The count of links.
     */
    public int getLinksCount() {
      return links_.size();
    }
    /**
     * <code>repeated string links = 5;</code>
     * @param index The index of the element to return.
     * @return The links at the given index.
     */
    public java.lang.String getLinks(int index) {
      return links_.get(index);
    }
    /**
     * <code>repeated string links = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the links at the given index.
     */
    public com.google.protobuf.ByteString
        getLinksBytes(int index) {
      return links_.getByteString(index);
    }
    /**
     * <code>repeated string links = 5;</code>
     * @param index The index to set the value at.
     * @param value The links to set.
     * @return This builder for chaining.
     */
    public Builder setLinks(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureLinksIsMutable();
      links_.set(index, value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string links = 5;</code>
     * @param value The links to add.
     * @return This builder for chaining.
     */
    public Builder addLinks(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureLinksIsMutable();
      links_.add(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string links = 5;</code>
     * @param values The links to add.
     * @return This builder for chaining.
     */
    public Builder addAllLinks(
        java.lang.Iterable<java.lang.String> values) {
      ensureLinksIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, links_);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string links = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearLinks() {
      links_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000010);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string links = 5;</code>
     * @param value The bytes of the links to add.
     * @return This builder for chaining.
     */
    public Builder addLinksBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureLinksIsMutable();
      links_.add(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList companies_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureCompaniesIsMutable() {
      if (!companies_.isModifiable()) {
        companies_ = new com.google.protobuf.LazyStringArrayList(companies_);
      }
      bitField0_ |= 0x00000020;
    }
    /**
     * <code>repeated string companies = 6;</code>
     * @return A list containing the companies.
     */
    public com.google.protobuf.ProtocolStringList
        getCompaniesList() {
      companies_.makeImmutable();
      return companies_;
    }
    /**
     * <code>repeated string companies = 6;</code>
     * @return The count of companies.
     */
    public int getCompaniesCount() {
      return companies_.size();
    }
    /**
     * <code>repeated string companies = 6;</code>
     * @param index The index of the element to return.
     * @return The companies at the given index.
     */
    public java.lang.String getCompanies(int index) {
      return companies_.get(index);
    }
    /**
     * <code>repeated string companies = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the companies at the given index.
     */
    public com.google.protobuf.ByteString
        getCompaniesBytes(int index) {
      return companies_.getByteString(index);
    }
    /**
     * <code>repeated string companies = 6;</code>
     * @param index The index to set the value at.
     * @param value The companies to set.
     * @return This builder for chaining.
     */
    public Builder setCompanies(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureCompaniesIsMutable();
      companies_.set(index, value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string companies = 6;</code>
     * @param value The companies to add.
     * @return This builder for chaining.
     */
    public Builder addCompanies(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureCompaniesIsMutable();
      companies_.add(value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string companies = 6;</code>
     * @param values The companies to add.
     * @return This builder for chaining.
     */
    public Builder addAllCompanies(
        java.lang.Iterable<java.lang.String> values) {
      ensureCompaniesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, companies_);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string companies = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCompanies() {
      companies_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000020);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string companies = 6;</code>
     * @param value The bytes of the companies to add.
     * @return This builder for chaining.
     */
    public Builder addCompaniesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureCompaniesIsMutable();
      companies_.add(value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:CVResponse)
  }

  // @@protoc_insertion_point(class_scope:CVResponse)
  private static final CVResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CVResponse();
  }

  public static CVResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CVResponse>
      PARSER = new com.google.protobuf.AbstractParser<CVResponse>() {
    @java.lang.Override
    public CVResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CVResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CVResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public CVResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

