// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/cv.proto
// Protobuf Java Version: 4.27.0

public interface GetAllRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllRequest)
    com.google.protobuf.MessageOrBuilder {
}
