// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/cv.proto
// Protobuf Java Version: 4.27.0

public interface GetAllResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .CVResponse cvs = 1;</code>
   */
  java.util.List<CVResponse> 
      getCvsList();
  /**
   * <code>repeated .CVResponse cvs = 1;</code>
   */
  CVResponse getCvs(int index);
  /**
   * <code>repeated .CVResponse cvs = 1;</code>
   */
  int getCvsCount();
  /**
   * <code>repeated .CVResponse cvs = 1;</code>
   */
  java.util.List<? extends CVResponseOrBuilder> 
      getCvsOrBuilderList();
  /**
   * <code>repeated .CVResponse cvs = 1;</code>
   */
  CVResponseOrBuilder getCvsOrBuilder(
      int index);
}
