// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/cv.proto
// Protobuf Java Version: 4.27.0

/**
 * Protobuf type {@code GetAllResponse}
 */
public final class GetAllResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:GetAllResponse)
    GetAllResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      GetAllResponse.class.getName());
  }
  // Use GetAllResponse.newBuilder() to construct.
  private GetAllResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetAllResponse() {
    cvs_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Cv.internal_static_GetAllResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Cv.internal_static_GetAllResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            GetAllResponse.class, GetAllResponse.Builder.class);
  }

  public static final int CVS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<CVResponse> cvs_;
  /**
   * <code>repeated .CVResponse cvs = 1;</code>
   */
  @java.lang.Override
  public java.util.List<CVResponse> getCvsList() {
    return cvs_;
  }
  /**
   * <code>repeated .CVResponse cvs = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends CVResponseOrBuilder> 
      getCvsOrBuilderList() {
    return cvs_;
  }
  /**
   * <code>repeated .CVResponse cvs = 1;</code>
   */
  @java.lang.Override
  public int getCvsCount() {
    return cvs_.size();
  }
  /**
   * <code>repeated .CVResponse cvs = 1;</code>
   */
  @java.lang.Override
  public CVResponse getCvs(int index) {
    return cvs_.get(index);
  }
  /**
   * <code>repeated .CVResponse cvs = 1;</code>
   */
  @java.lang.Override
  public CVResponseOrBuilder getCvsOrBuilder(
      int index) {
    return cvs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < cvs_.size(); i++) {
      output.writeMessage(1, cvs_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < cvs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, cvs_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof GetAllResponse)) {
      return super.equals(obj);
    }
    GetAllResponse other = (GetAllResponse) obj;

    if (!getCvsList()
        .equals(other.getCvsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCvsCount() > 0) {
      hash = (37 * hash) + CVS_FIELD_NUMBER;
      hash = (53 * hash) + getCvsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static GetAllResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetAllResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetAllResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetAllResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetAllResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetAllResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetAllResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static GetAllResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static GetAllResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static GetAllResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static GetAllResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static GetAllResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(GetAllResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetAllResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetAllResponse)
      GetAllResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Cv.internal_static_GetAllResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Cv.internal_static_GetAllResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GetAllResponse.class, GetAllResponse.Builder.class);
    }

    // Construct using GetAllResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (cvsBuilder_ == null) {
        cvs_ = java.util.Collections.emptyList();
      } else {
        cvs_ = null;
        cvsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Cv.internal_static_GetAllResponse_descriptor;
    }

    @java.lang.Override
    public GetAllResponse getDefaultInstanceForType() {
      return GetAllResponse.getDefaultInstance();
    }

    @java.lang.Override
    public GetAllResponse build() {
      GetAllResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public GetAllResponse buildPartial() {
      GetAllResponse result = new GetAllResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(GetAllResponse result) {
      if (cvsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          cvs_ = java.util.Collections.unmodifiableList(cvs_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.cvs_ = cvs_;
      } else {
        result.cvs_ = cvsBuilder_.build();
      }
    }

    private void buildPartial0(GetAllResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof GetAllResponse) {
        return mergeFrom((GetAllResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(GetAllResponse other) {
      if (other == GetAllResponse.getDefaultInstance()) return this;
      if (cvsBuilder_ == null) {
        if (!other.cvs_.isEmpty()) {
          if (cvs_.isEmpty()) {
            cvs_ = other.cvs_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCvsIsMutable();
            cvs_.addAll(other.cvs_);
          }
          onChanged();
        }
      } else {
        if (!other.cvs_.isEmpty()) {
          if (cvsBuilder_.isEmpty()) {
            cvsBuilder_.dispose();
            cvsBuilder_ = null;
            cvs_ = other.cvs_;
            bitField0_ = (bitField0_ & ~0x00000001);
            cvsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getCvsFieldBuilder() : null;
          } else {
            cvsBuilder_.addAllMessages(other.cvs_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              CVResponse m =
                  input.readMessage(
                      CVResponse.parser(),
                      extensionRegistry);
              if (cvsBuilder_ == null) {
                ensureCvsIsMutable();
                cvs_.add(m);
              } else {
                cvsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<CVResponse> cvs_ =
      java.util.Collections.emptyList();
    private void ensureCvsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        cvs_ = new java.util.ArrayList<CVResponse>(cvs_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        CVResponse, CVResponse.Builder, CVResponseOrBuilder> cvsBuilder_;

    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public java.util.List<CVResponse> getCvsList() {
      if (cvsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(cvs_);
      } else {
        return cvsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public int getCvsCount() {
      if (cvsBuilder_ == null) {
        return cvs_.size();
      } else {
        return cvsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public CVResponse getCvs(int index) {
      if (cvsBuilder_ == null) {
        return cvs_.get(index);
      } else {
        return cvsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public Builder setCvs(
        int index, CVResponse value) {
      if (cvsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCvsIsMutable();
        cvs_.set(index, value);
        onChanged();
      } else {
        cvsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public Builder setCvs(
        int index, CVResponse.Builder builderForValue) {
      if (cvsBuilder_ == null) {
        ensureCvsIsMutable();
        cvs_.set(index, builderForValue.build());
        onChanged();
      } else {
        cvsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public Builder addCvs(CVResponse value) {
      if (cvsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCvsIsMutable();
        cvs_.add(value);
        onChanged();
      } else {
        cvsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public Builder addCvs(
        int index, CVResponse value) {
      if (cvsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCvsIsMutable();
        cvs_.add(index, value);
        onChanged();
      } else {
        cvsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public Builder addCvs(
        CVResponse.Builder builderForValue) {
      if (cvsBuilder_ == null) {
        ensureCvsIsMutable();
        cvs_.add(builderForValue.build());
        onChanged();
      } else {
        cvsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public Builder addCvs(
        int index, CVResponse.Builder builderForValue) {
      if (cvsBuilder_ == null) {
        ensureCvsIsMutable();
        cvs_.add(index, builderForValue.build());
        onChanged();
      } else {
        cvsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public Builder addAllCvs(
        java.lang.Iterable<? extends CVResponse> values) {
      if (cvsBuilder_ == null) {
        ensureCvsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, cvs_);
        onChanged();
      } else {
        cvsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public Builder clearCvs() {
      if (cvsBuilder_ == null) {
        cvs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        cvsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public Builder removeCvs(int index) {
      if (cvsBuilder_ == null) {
        ensureCvsIsMutable();
        cvs_.remove(index);
        onChanged();
      } else {
        cvsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public CVResponse.Builder getCvsBuilder(
        int index) {
      return getCvsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public CVResponseOrBuilder getCvsOrBuilder(
        int index) {
      if (cvsBuilder_ == null) {
        return cvs_.get(index);  } else {
        return cvsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public java.util.List<? extends CVResponseOrBuilder> 
         getCvsOrBuilderList() {
      if (cvsBuilder_ != null) {
        return cvsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(cvs_);
      }
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public CVResponse.Builder addCvsBuilder() {
      return getCvsFieldBuilder().addBuilder(
          CVResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public CVResponse.Builder addCvsBuilder(
        int index) {
      return getCvsFieldBuilder().addBuilder(
          index, CVResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public java.util.List<CVResponse.Builder> 
         getCvsBuilderList() {
      return getCvsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        CVResponse, CVResponse.Builder, CVResponseOrBuilder> 
        getCvsFieldBuilder() {
      if (cvsBuilder_ == null) {
        cvsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            CVResponse, CVResponse.Builder, CVResponseOrBuilder>(
                cvs_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        cvs_ = null;
      }
      return cvsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:GetAllResponse)
  }

  // @@protoc_insertion_point(class_scope:GetAllResponse)
  private static final GetAllResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new GetAllResponse();
  }

  public static GetAllResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetAllResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetAllResponse>() {
    @java.lang.Override
    public GetAllResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetAllResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetAllResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public GetAllResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

